In [2]:
import pandas as pd
import glob
import os

In [3]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202301_성남시.csv"

# 파일 존재 여부 먼저 확인
print(os.path.exists(file_path))

# True가 나오면 실행
df = pd.read_csv(file_path, nrows=5, encoding="utf-8-sig")

df

True

,ETL_YM,DOW,D_TIME_CD,D_CTY_CD,D_MEGA_NM,D_CTY_NM,D_CENTER_X,D_CENTER_Y,TRANS_GB,SEX_CD,AGE_GRP,CNT
0,202301,월,21,41135,경기도,성남시 분당구,965120,1931210,1,W,2,1459.27
1,202301,일,13,41133,경기도,성남시 중원구,970268,1937199,0,M,6,3192.18
2,202301,화,14,41133,경기도,성남시 중원구,970268,1937199,7,M,9,43.18
3,202301,수,22,41131,경기도,성남시 수정구,964981,1937423,0,W,6,1477.35
4,202301,토,20,41135,경기도,성남시 분당구,965120,1931210,3,W,1,229.50

In [6]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202301_성남시.csv"

# 파일 존재 여부 먼저 확인
print(os.path.exists(file_path))

# True가 나오면 실행
df_2 = pd.read_csv(file_path, nrows=5, encoding="utf-8-sig")

df_2

True

,ETL_YMD,D_TIME_CD,D_ADMI_CD,D_MEGA_NM,D_CTY_NM,D_ADMI_NM,D_CENTER_X,D_CENTER_Y,TRANS_GB,SEX_CD,AGE_GRP,CNT
0,20230124,19,41135650,경기도,성남시 분당구,판교동,963992,1932720,7,M,5,17.14
1,20230115,10,41133660,경기도,성남시 중원구,하대원동,968696,1936625,1,M,2,3.38
2,20230108,9,41133510,경기도,성남시 중원구,성남동,967502,1936961,2,M,2,8.64
3,20230125,16,41133560,경기도,성남시 중원구,은행2동,971264,1940268,7,M,4,3.37
4,20230127,10,41135560,경기도,성남시 분당구,정자2동,966201,1929810,7,M,6,5.08

In [ ]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202301_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202302_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202303_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202304_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202305_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202306_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202307_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202308_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202309_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202310_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202311_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202312_성남시.csv

In [21]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\2023_통합.csv"

In [ ]:
if os.path.exists(output_file):
    os.remove(output_file)
first = True

In [24]:
for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [25]:
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

In [28]:
pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-2026.3.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: pandas>=1.5.0 in c:\Users\cute3\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fastparquet) (3.0.2)
Requirement already satisfied: numpy in c:\Users\cute3\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fastparquet) (2.4.4)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.11.0-cp312-cp312-win_amd64.whl.metadata (681 bytes)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in c:\Users\cute3\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\cute3\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\cute3\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\cute3\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2026.3.0-cp312-cp312-win_amd64.whl (667 kB)
   ---------------------------------------- 0.0/667.9 kB ? eta -:--:--
   ------------------------------- -------- 524.3/667.9 kB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 667.9/667.9 kB 3.7 MB/s  0:00:00
Downloading cramjam-2.11.0-cp312-cp312-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------------ --------------- 1.0/1.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 5.8 MB/s  0:00:00
Downloading fsspec-2026.3.0-py3-none-any.whl (202 kB)
Installing collected packages: fsspec, cramjam, fastparquet

   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ------------- -------------------------- 1/3 [cramjam]
   -------------------------- ------------- 2/3 [fastparquet]
   -------------------------- ------------- 2/3 [fastparquet]
   ---------------------------------------- 3/3 [fastparquet]

Successfully installed cramjam-2.11.0 fastparquet-2026.3.0 fsspec-2026.3.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

## 2024

In [30]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\*.csv"
    )
)

In [ ]:
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202401_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202402_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202403_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202404_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202405_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202406_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202407_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202408_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202409_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202410_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202411_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202412_성남시.csv

In [32]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\2024_통합.csv"

In [33]:
if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2024 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202401_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202402_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202403_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202404_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202405_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202406_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202407_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202408_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202409_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202410_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202411_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202412_성남시.csv
✅ 2024 통합 완료

In [35]:
df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\2024_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

## 2025

In [3]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\*.csv"
    )
)

In [4]:
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202501_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202502_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202503_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202504_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202505_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202506_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202507_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202508_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202509_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202510_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202511_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202512_성남시.csv

In [6]:
for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2025 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202501_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202502_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202503_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202504_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202505_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202506_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202507_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202508_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202509_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202510_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202511_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\T11_GG_TRANS_SEXAGE_ADMI_OUTFLOW_202512_성남시.csv
✅ 2025 통합 완료

In [7]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\2025_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\2025_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

In [9]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2025\2025_확인.parquet")

In [10]:
# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

In [11]:
# parquet 저장
df_all.to_parquet("t11_all.parquet", index=False)

## t5

In [3]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\*.csv"
    )
)

In [4]:
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202301_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202302_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202303_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202304_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202305_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202306_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202307_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202308_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202309_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202310_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202311_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202312_성남시.csv

In [6]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

In [7]:
for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [8]:
# 파일 경로
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\2023_통합.csv"

# 컬럼명만 확인 (전체 파일 다 안 읽고 빠르게)
df = pd.read_csv(file_path, nrows=5, encoding='utf-8-sig')

df.columns.tolist()

['ETL_YMD',
 'D_TIME_CD',
 'D_ADMI_CD',
 'D_MEGA_NM',
 'D_CTY_NM',
 'D_ADMI_NM',
 'D_CENTER_X',
 'D_CENTER_Y',
 'PURPOSE',
 'SEX_CD',
 'AGE_GRP',
 'CNT']

In [10]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

## 2024

In [11]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\*.csv"
    )
)

In [12]:
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202401_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202402_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202403_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202404_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202405_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202406_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202407_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202408_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202409_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202410_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202411_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202412_성남시.csv

In [13]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\2024_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

In [14]:
for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2024 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202401_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202402_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202403_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202404_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202405_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202406_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202407_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202408_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202409_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202410_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202411_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202412_성남시.csv
✅ 2024 통합 완료

In [16]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\2024_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\2024_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

## 2025

In [17]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\*.csv"
    )
)

In [18]:
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202501_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202502_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202503_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202504_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202505_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202506_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202507_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202508_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202509_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202510_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202511_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202512_성남시.csv

In [19]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\2025_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

In [20]:
for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2025 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202501_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202502_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202503_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202504_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202505_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202506_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202507_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202508_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202509_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202510_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202511_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\T5_GG_PURPOSE_SEXAGE_ADMI_INFLOW_202512_성남시.csv
✅ 2025 통합 완료

In [21]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\2025_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\2025_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

In [23]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T5\2025\2025_확인.parquet")

# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

# parquet 저장
df_all.to_parquet("t5_all.parquet", index=False)

## t7

In [24]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\*.csv"
    )
)

In [25]:
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202301_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202302_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202303_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202304_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202305_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202306_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202307_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202308_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202309_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202310_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202311_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202312_성남시.csv

In [26]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [27]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\2023_통합.csv"

# 컬럼명만 확인 (전체 파일 다 안 읽고 빠르게)
df = pd.read_csv(file_path, nrows=5, encoding='utf-8-sig')

df.columns.tolist()

['ETL_YMD',
 'D_TIME_CD',
 'D_ADMI_CD',
 'D_MEGA_NM',
 'D_CTY_NM',
 'D_ADMI_NM',
 'D_CENTER_X',
 'D_CENTER_Y',
 'TRANS_GB',
 'SEX_CD',
 'AGE_GRP',
 'CNT']

In [ ]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202301_성남시.csv"

# 컬럼명 확인
df = pd.read_csv(file_path, nrows=5, encoding='utf-8-sig')

print(df.columns.tolist())

['ETL_YMD', 'D_TIME_CD', 'D_ADMI_CD', 'D_MEGA_NM', 'D_CTY_NM', 'D_ADMI_NM', 'D_CENTER_X', 'D_CENTER_Y', 'TRANS_GB', 'SEX_CD', 'AGE_GRP', 'CNT']

In [30]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

## 2024

In [31]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\*.csv"
    )
)

In [ ]:
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202401_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202402_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202403_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202404_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202405_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202406_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202407_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202408_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202409_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202410_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202411_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202412_성남시.csv

In [33]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\2024_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2024 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202401_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202402_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202403_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202404_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202405_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202406_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202407_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202408_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202409_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202410_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202411_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202412_성남시.csv
✅ 2024 통합 완료

In [2]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\2024_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\2024_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

## 2025

In [3]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\*.csv"
    )
)

In [4]:
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202501_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202502_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202503_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202504_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202505_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202506_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202507_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202508_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202509_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202510_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202511_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202512_성남시.csv

In [5]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\2025_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2025 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202501_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202502_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202503_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202504_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202505_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202506_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202507_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202508_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202509_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202510_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202511_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202512_성남시.csv
✅ 2025 통합 완료

In [6]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\2025_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\2025_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

In [47]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\2025_확인.parquet")

# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

# parquet 저장
df_all.to_parquet("t7_all.parquet", index=False)

## t4

In [ ]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202301_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202302_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202303_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202304_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202305_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202306_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202307_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202308_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202309_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202310_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202311_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202312_성남시.csv

In [10]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202301_성남시.csv"

# 컬럼명 확인
df = pd.read_csv(file_path, nrows=5, encoding='utf-8-sig')

print(df.columns.tolist())

['ETL_YM', 'DOW', 'D_TIME_CD', 'D_CTY_CD', 'D_MEGA_NM', 'D_CTY_NM', 'D_CENTER_X', 'D_CENTER_Y', 'PURPOSE', 'SEX_CD', 'AGE_GRP', 'CNT']

In [11]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [13]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2024

In [14]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202401_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202402_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202403_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202404_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202405_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202406_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202407_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202408_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202409_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202410_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202411_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202412_성남시.csv

In [15]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\2024_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2024 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202401_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202402_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202403_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202404_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202405_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202406_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202407_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202408_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202409_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202410_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202411_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202412_성남시.csv
✅ 2024 통합 완료

In [16]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\2024_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\2024_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2025

In [17]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202501_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202502_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202503_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202504_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202505_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202506_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202507_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202508_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202509_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202510_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202511_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202512_성남시.csv

In [18]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\2025_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2025 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202501_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202502_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202503_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202504_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202505_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202506_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202507_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202508_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202509_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202510_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202511_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\T4_GG_PURPOSE_SEXAGE_SGG_INFLOW_202512_성남시.csv
✅ 2025 통합 완료

In [22]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\2025_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\2025_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

In [ ]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T4\2025\2025_확인.parquet")

# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

# parquet 저장
df_all.to_parquet("t4_all.parquet", index=False)

## t6

In [31]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\*.csv"
    )
)
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202301_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202302_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202303_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202304_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202305_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202306_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202307_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202308_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202309_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202310_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202311_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202312_성남시.csv

In [32]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [1]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202301_성남시.csv"

# 파일 존재 여부 먼저 확인
print(os.path.exists(file_path))

# True가 나오면 실행
df = pd.read_csv(file_path, nrows=5, encoding="utf-8-sig")

df

NameError: name 'os' is not defined

In [36]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [37]:
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

## 2024

In [39]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\*.csv"
    )
)
print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202401_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202402_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202403_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202404_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202405_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202406_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202407_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202408_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202409_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202410_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202411_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202412_성남시.csv

In [40]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\2024_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2024 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202401_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202402_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202403_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202404_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202405_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202406_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202407_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202408_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202409_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202410_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202411_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202412_성남시.csv
✅ 2024 통합 완료

In [41]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\2024_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\2024_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2025

In [42]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202501_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202502_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202503_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202504_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202505_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202506_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202507_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202508_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202509_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202510_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202511_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202512_성남시.csv

In [43]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\2025_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2025 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202501_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202502_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202503_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202504_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202505_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202506_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202507_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202508_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202509_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202510_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202511_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\T6_GG_TRANS_SEXAGE_SGG_INFLOW_202512_성남시.csv
✅ 2025 통합 완료

In [44]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\2025_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\2025_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

In [46]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T6\2025\2025_확인.parquet")

# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

# parquet 저장
df_all.to_parquet("t6_all.parquet", index=False)

# t8

In [48]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202301_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202302_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202303_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202304_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202305_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202306_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202307_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202308_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202309_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202310_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202311_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202312_성남시.csv

In [49]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202301_성남시.csv"

# 컬럼명 확인
df = pd.read_csv(file_path, nrows=5, encoding='utf-8-sig')

print(df.columns.tolist())

['ETL_YM', 'DOW', 'O_TIME_CD', 'O_CTY_CD', 'O_MEGA_NM', 'O_CTY_NM', 'O_CENTER_X', 'O_CENTER_Y', 'PURPOSE', 'SEX_CD', 'AGE_GRP', 'CNT']

In [50]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [51]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2024

In [52]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202401_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202402_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202403_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202404_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202405_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202406_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202407_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202408_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202409_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202410_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202411_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202412_성남시.csv

In [53]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\2024_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2024 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202401_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202402_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202403_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202404_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202405_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202406_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202407_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202408_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202409_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202410_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202411_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202412_성남시.csv
✅ 2024 통합 완료

In [54]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\2024_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\2024_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2025

In [55]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202501_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202502_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202503_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202504_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202505_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202506_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202507_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202508_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202509_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202510_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202511_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202512_성남시.csv

In [56]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\2025_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2025 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202501_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202502_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202503_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202504_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202505_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202506_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202507_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202508_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202509_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202510_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202511_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\T8_GG_PURPOSE_SEXAGE_SGG_OUTFLOW_202512_성남시.csv
✅ 2025 통합 완료

In [57]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\2025_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\2025_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

In [58]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T8\2025\2025_확인.parquet")

# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

# parquet 저장
df_all.to_parquet("t8_all.parquet", index=False)

# t9

In [59]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202301_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202302_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202303_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202304_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202305_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202306_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202307_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202308_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202309_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202310_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202311_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202312_성남시.csv

In [60]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202301_성남시.csv"

# 컬럼명 확인
df = pd.read_csv(file_path, nrows=5, encoding='utf-8-sig')

df.columns.tolist()

['ETL_YMD',
 'O_TIME_CD',
 'O_ADMI_CD',
 'O_MEGA_NM',
 'O_CTY_NM',
 'O_ADMI_NM',
 'O_CENTER_X',
 'O_CENTER_Y',
 'PURPOSE',
 'SEX_CD',
 'AGE_GRP',
 'CNT']

In [63]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [64]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2024

In [65]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202401_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202402_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202403_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202404_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202405_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202406_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202407_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202408_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202409_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202410_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202411_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202412_성남시.csv

In [66]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\2024_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2024 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202401_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202402_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202403_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202404_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202405_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202406_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202407_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202408_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202409_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202410_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202411_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202412_성남시.csv
✅ 2024 통합 완료

In [67]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\2024_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\2024_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2025

In [68]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202501_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202502_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202503_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202504_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202505_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202506_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202507_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202508_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202509_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202510_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202511_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202512_성남시.csv

In [69]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\2025_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2025 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202501_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202502_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202503_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202504_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202505_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202506_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202507_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202508_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202509_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202510_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202511_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\T9_GG_PURPOSE_SEXAGE_ADMI_OUTFLOW_202512_성남시.csv
✅ 2025 통합 완료

In [70]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\2025_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\2025_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

In [71]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T9\2025\2025_확인.parquet")

# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

# parquet 저장
df_all.to_parquet("t9_all.parquet", index=False)

# t10

In [72]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202301_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202302_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202303_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202304_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202305_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202306_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202307_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202308_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202309_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202310_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202311_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202312_성남시.csv

In [74]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202301_성남시.csv"

# 컬럼명 확인
df = pd.read_csv(file_path, nrows=5, encoding='utf-8-sig')

df.columns.tolist()

['ETL_YM',
 'DOW',
 'O_TIME_CD',
 'O_CTY_CD',
 'O_MEGA_NM',
 'O_CTY_NM',
 'O_CENTER_X',
 'O_CENTER_Y',
 'TRANS_GB',
 'SEX_CD',
 'AGE_GRP',
 'CNT']

In [75]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202301_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202302_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202303_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202304_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202305_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202306_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202307_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202308_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202309_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202310_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202311_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202312_성남시.csv
✅ 2023 통합 완료

In [76]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2024

In [77]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202401_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202402_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202403_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202404_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202405_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202406_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202407_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202408_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202409_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202410_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202411_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202412_성남시.csv

In [78]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\2024_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2024 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202401_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202402_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202403_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202404_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202405_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202406_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202407_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202408_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202409_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202410_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202411_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202412_성남시.csv
✅ 2024 통합 완료

In [79]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\2024_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\2024_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

# 2025

In [80]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)

파일 개수: 12
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202501_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202502_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202503_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202504_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202505_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202506_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202507_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202508_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202509_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202510_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202511_성남시.csv
C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202512_성남시.csv

In [81]:
# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\2025_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2025 통합 완료")

처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202501_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202502_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202503_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202504_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202505_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202506_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202507_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202508_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202509_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202510_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202511_성남시.csv
처리 중: C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\T10_GG_TRANS_SEXAGE_SGG_OUTFLOW_202512_성남시.csv
✅ 2025 통합 완료

In [82]:
# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\2025_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\2025_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

✅ parquet 저장 완료

In [83]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T10\2025\2025_확인.parquet")

# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

# parquet 저장
df_all.to_parquet("t10_all.parquet", index=False)

In [ ]:
files = sorted(
    glob.glob(
        r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\*.csv"
    )
)

print("파일 개수:", len(files))
for f in files:
    print(f)


# 코드이름 바꿔서 저장
output_file = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\2023_통합.csv"

if os.path.exists(output_file):
    os.remove(output_file)
first = True

for file in files:
    print(f"처리 중: {file}")

    for chunk in pd.read_csv(file, chunksize=100000, encoding="utf-8-sig"):
        chunk.columns = chunk.columns.str.strip()

        if first:
            chunk.to_csv(output_file, index=False, mode="w", encoding="utf-8-sig")
            first = False
        else:
            chunk.to_csv(output_file, index=False, mode="a", header=False, encoding="utf-8-sig")

print("✅ 2023 통합 완료")

# 파케이 변환
df = pd.read_csv(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\2023_통합.csv",
    encoding="utf-8-sig"
)

df.to_parquet(
    r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T11\2023\2023_확인.parquet",
    index=False
)

print("✅ parquet 저장 완료")

In [ ]:
file_path = r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\T7_GG_TRANS_SEXAGE_ADMI_INFLOW_202301_성남시.csv"

# 컬럼명 확인
df = pd.read_csv(file_path, nrows=5, encoding='utf-8-sig')

print(df.columns.tolist())

In [ ]:
# parquet 불러오기
df_2023 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2023\2023_확인.parquet")
df_2024 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2024\2024_확인.parquet")
df_2025 = pd.read_parquet(r"C:\Users\cute3\OneDrive\Desktop\성남시\통신\T7\2025\2025_확인.parquet")

# 세로 통합
df_all = pd.concat(
    [df_2023, df_2024, df_2025],
    axis=0,
    ignore_index=True
)

# parquet 저장
df_all.to_parquet("t7_all.parquet", index=False)