In [40]:
import pandas as pd
import glob
import os

## 지하철 결측치 / 이상치

In [41]:
file_path = "../Data/subway.csv"

# 파일 존재 여부 먼저 확인
print(os.path.exists(file_path))

# True가 나오면 실행
df_subway = pd.read_csv(file_path, encoding="utf-8-sig")

df_subway.head(5)

True

         월  노선명                역명  월별_승차합계  월별_하차합계
0  2023-01  분당선               가천대   182889   200114
1  2023-01  8호선               남위례   159937   165440
2  2023-01  8호선  남한산성입구(성남법원.검찰청)   349153   313708
3  2023-01  8호선             단대오거리   312021   304362
4  2023-01  8호선                모란   131234   106478

In [42]:
df_subway.shape

(850, 5)

In [43]:
df_subway.dtypes

월            str
노선명          str
역명           str
월별_승차합계    int64
월별_하차합계    int64
dtype: object

In [44]:
df_subway.isnull().sum()

월          0
노선명        0
역명         0
월별_승차합계    0
월별_하차합계    0
dtype: int64

In [45]:
df_subway.to_csv('2차전처리_지하철데이터.csv', index=False, encoding='utf-8-sig')

## 버스 결측치 / 이상치

In [46]:
import pandas as pd
import glob
import os

In [47]:
file_path = "../Data/bus_plz.csv"

# 파일 존재 여부 먼저 확인
print(os.path.exists(file_path))

# True가 나오면 실행
df_bus = pd.read_csv(file_path, encoding="utf-8-sig")

df_bus.head(5)

True

C:\Users\cute3\AppData\Local\Temp\ipykernel_25832\3567098626.py:7: DtypeWarning: Columns (0: 정류소번호) have mixed types. Specify dtype option on import or set low_memory=False.
  df_bus = pd.read_csv(file_path, encoding="utf-8-sig")

        승하차일자 관할관청   행정동      정류소ID   정류소번호         정류소명  승차합계   초승   환승   하차
0  2023-01-01  성남시   성남동  205000120  6163.0   (구)성남동주민센터   103   99    4  106
1  2023-01-01  성남시  서현1동  206000436  7387.0      AK플라자2층   353  203  150  454
2  2023-01-01  성남시   삼평동  206000677  7034.0  H스퀘어.삼환하이펙스     1    1    0   25
3  2023-01-01  성남시   삼평동  206000677  7034.0  H스퀘어.삼환하이펙스     1    1    0   25
4  2023-01-01  성남시   삼평동  206000678  7479.0  H스퀘어.삼환하이펙스    15   14    1    2

In [48]:
df_bus.shape

(2058750, 10)

In [49]:
df_bus.dtypes

승하차일자       str
관할관청        str
행정동         str
정류소ID     int64
정류소번호    object
정류소명        str
승차합계      int64
초승        int64
환승        int64
하차        int64
dtype: object

In [50]:
df_bus.isnull().sum()

승하차일자        0
관할관청         0
행정동      65110
정류소ID        0
정류소번호     2540
정류소명         6
승차합계         0
초승           0
환승           0
하차           0
dtype: int64

In [51]:
# 정류소 와 행정동이 모두 nan값인 행 찾기
result = df_bus[
    (df_bus['정류소명'].notna()) &
    (df_bus['행정동'].isna())
]

result

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
17,2023-01-01,성남시,NaN,206000855,7822.0,SK.금강테라스하우스,11,10,1,24
48,2023-01-01,성남시,NaN,204000001,5008.0,고등동우체국.성남농협대왕지점,89,60,29,178
84,2023-01-01,성남시,NaN,204000256,5221.0,교보문고(마을),11,11,0,30
94,2023-01-01,성남시,NaN,205000008,6076.0,구서고.금상초교,389,378,11,244
95,2023-01-01,성남시,NaN,205000160,6074.0,구서고.금상초교,317,303,14,332
...,...,...,...,...,...,...,...,...,...,...
2058599,2025-12-31,성남시,NaN,205000016,06025,하대원동행정복지센터.영성중.검단초,406,360,46,686
2058600,2025-12-31,성남시,NaN,205000152,06024,하대원동행정복지센터.영성중.검단초,731,688,43,352
2058647,2025-12-31,성남시,NaN,204000070,05151,한국폴리텍대학.성남문화예술교육센터,27,23,4,37
2058648,2025-12-31,성남시,NaN,204000080,05149,한국폴리텍대학.성남문화예술교육센터,8,4,4,36
2058688,2025-12-31,성남시,NaN,206000342,07318,현대노블리스,0,0,0,12

In [52]:
df_bus[
    (df_bus['정류소ID'] == 206000617) &
    (df_bus['정류소명'] == '성남역.보평중고등학교')
]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
766909,2024-03-19,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,68,62,6,114
766910,2024-03-19,성남시,삼평동,206000617,7557.0,성남역.보평중고등학교,68,62,6,114
786148,2024-03-30,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,43,37,6,81
786149,2024-03-30,성남시,삼평동,206000617,7557.0,성남역.보평중고등학교,43,37,6,81
787889,2024-03-31,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,45,26,19,85
...,...,...,...,...,...,...,...,...,...,...
2053479,2025-12-29,성남시,삼평동,206000617,07557,성남역.보평중고등학교,42,27,15,140
2055589,2025-12-30,성남시,백현동,206000617,07557,성남역.보평중고등학교,35,25,10,122
2055590,2025-12-30,성남시,삼평동,206000617,07557,성남역.보평중고등학교,35,25,10,122
2057690,2025-12-31,성남시,백현동,206000617,07557,성남역.보평중고등학교,37,28,9,106
2057691,2025-12-31,성남시,삼평동,206000617,07557,성남역.보평중고등학교,37,28,9,106

In [53]:
df_bus[
    (df_bus['정류소ID'] == 206000616) &
    (df_bus['정류소명'] == '성남역.보평중고등학교') 
]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
766907,2024-03-19,성남시,백현동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81
766908,2024-03-19,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81
786146,2024-03-30,성남시,백현동,206000616,7556.0,성남역.보평중고등학교,63,39,24,40
786147,2024-03-30,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,63,39,24,40
787887,2024-03-31,성남시,백현동,206000616,7556.0,성남역.보평중고등학교,54,42,12,30
...,...,...,...,...,...,...,...,...,...,...
2053477,2025-12-29,성남시,삼평동,206000616,07556,성남역.보평중고등학교,187,157,30,88
2055587,2025-12-30,성남시,백현동,206000616,07556,성남역.보평중고등학교,194,168,26,104
2055588,2025-12-30,성남시,삼평동,206000616,07556,성남역.보평중고등학교,194,168,26,104
2057688,2025-12-31,성남시,백현동,206000616,07556,성남역.보평중고등학교,223,184,39,82
2057689,2025-12-31,성남시,삼평동,206000616,07556,성남역.보평중고등학교,223,184,39,82

In [54]:
# 백현동쪽 버스정류장 -> 삼평동 없애야 함
df_bus[
    (df_bus['정류소ID'] == 206000617) &
    (df_bus['정류소명'] == '성남역.보평중고등학교') &
    (df_bus['승하차일자'] == '2024-03-30') 
]

             승하차일자 관할관청  행정동      정류소ID   정류소번호         정류소명  승차합계  초승  환승  하차
786148  2024-03-30  성남시  백현동  206000617  7557.0  성남역.보평중고등학교    43  37   6  81
786149  2024-03-30  성남시  삼평동  206000617  7557.0  성남역.보평중고등학교    43  37   6  81

In [55]:
# 모든 날짜에서 행정동이 삼평동인 행 삭제

df_bus = df_bus[
    ~(
        (df_bus['정류소ID'] == 206000617) &
        (df_bus['정류소명'] == '성남역.보평중고등학교') &
        (df_bus['행정동'] == '삼평동')
    )
]

# 확인
df_bus[
    (df_bus['정류소ID'] == 206000617) &
    (df_bus['정류소명'] == '성남역.보평중고등학교')
]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
766909,2024-03-19,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,68,62,6,114
786148,2024-03-30,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,43,37,6,81
787889,2024-03-31,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,45,26,19,85
789638,2024-04-01,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,37,31,6,127
791396,2024-04-02,성남시,백현동,206000617,7557.0,성남역.보평중고등학교,38,32,6,142
...,...,...,...,...,...,...,...,...,...,...
2049314,2025-12-27,성남시,백현동,206000617,07557,성남역.보평중고등학교,21,14,7,71
2051385,2025-12-28,성남시,백현동,206000617,07557,성남역.보평중고등학교,14,6,8,61
2053478,2025-12-29,성남시,백현동,206000617,07557,성남역.보평중고등학교,42,27,15,140
2055589,2025-12-30,성남시,백현동,206000617,07557,성남역.보평중고등학교,35,25,10,122
2057690,2025-12-31,성남시,백현동,206000617,07557,성남역.보평중고등학교,37,28,9,106

In [56]:
# 삼평동쪽 버스정류장 -> 백현동 없애야함
df_bus[
    (df_bus['정류소ID'] == 206000616) &
    (df_bus['정류소명'] == '성남역.보평중고등학교') &
    (df_bus['승하차일자'] == '2024-03-19') 
]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
766907,2024-03-19,성남시,백현동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81
766908,2024-03-19,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81

In [57]:
# 모든 날짜에서
# 정류소ID 206000616 + 성남역.보평중고등학교 중
# 행정동이 백현동인 행 삭제

df_bus = df_bus[
    ~(
        (df_bus['정류소ID'] == 206000616) &
        (df_bus['정류소명'] == '성남역.보평중고등학교') &
        (df_bus['행정동'] == '백현동')
    )
]

# 확인
df_bus[
    (df_bus['정류소ID'] == 206000616) &
    (df_bus['정류소명'] == '성남역.보평중고등학교')
]

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
766908,2024-03-19,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,127,125,2,81
786147,2024-03-30,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,63,39,24,40
787888,2024-03-31,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,54,42,12,30
789637,2024-04-01,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,148,139,9,59
791395,2024-04-02,성남시,삼평동,206000616,7556.0,성남역.보평중고등학교,165,145,20,64
...,...,...,...,...,...,...,...,...,...,...
2049313,2025-12-27,성남시,삼평동,206000616,07556,성남역.보평중고등학교,87,75,12,28
2051384,2025-12-28,성남시,삼평동,206000616,07556,성남역.보평중고등학교,64,51,13,34
2053477,2025-12-29,성남시,삼평동,206000616,07556,성남역.보평중고등학교,187,157,30,88
2055588,2025-12-30,성남시,삼평동,206000616,07556,성남역.보평중고등학교,194,168,26,104
2057689,2025-12-31,성남시,삼평동,206000616,07556,성남역.보평중고등학교,223,184,39,82

In [58]:
# 1) 정류소명 변경 매핑
name_map = {
    206000305: '성남역.이매고교.아름마을.효성선경아파트',
    206000314: '성남역.이매고교.아름마을.효성선경아파트',
    206000530: '성남역.백현마을2단지',
    206000537: '성남역.백현마을3단지',
}

for stop_id, new_name in name_map.items():
    df_bus.loc[df_bus['정류소ID'] == stop_id, '정류소명'] = new_name


# 2) 행정동 고정 매핑
dong_map = {
    206000305: '이매2동',
    206000314: '이매2동',
    206000530: '백현동',
    206000537: '백현동',
}

for stop_id, dong in dong_map.items():
    df_bus.loc[df_bus['정류소ID'] == stop_id, '행정동'] = dong

In [59]:
# -------------------------------------------------
# 206000616 / 7556
# -------------------------------------------------
df_bus['승하차일자'] = pd.to_datetime(df_bus['승하차일자'], errors='coerce')
mask_616 = (
    (pd.to_numeric(df_bus['정류소ID'], errors='coerce') == 206000616) &
    (pd.to_numeric(df_bus['정류소번호'], errors='coerce') == 7556)
)

# 1) 백현동 행 삭제
df_bus = df_bus[
    ~(
        mask_616 &
        (df_bus['행정동'] == '백현동')
    )
]

# 삭제 후 mask 다시 생성
mask_616 = (
    (pd.to_numeric(df_bus['정류소ID'], errors='coerce') == 206000616) &
    (pd.to_numeric(df_bus['정류소번호'], errors='coerce') == 7556)
)

# 2) 2023년이고 정류소명이 NaN이면 채우기
df_bus.loc[
    mask_616 &
    (df_bus['승하차일자'].dt.year == 2023) &
    (df_bus['정류소명'].isna()),
    '정류소명'
] = '보평중고등학교'

# 3) 2024년이고 정류소명이 NaN이면 채우기
df_bus.loc[
    mask_616 &
    (df_bus['승하차일자'].dt.year == 2024) &
    (df_bus['정류소명'].isna()),
    '정류소명'
] = '성남역.보평중고등학교'

In [60]:
# -------------------------------------------------
# 206000617 / 7557
# -------------------------------------------------

# 승하차일자 날짜형 변환
df_bus['승하차일자'] = pd.to_datetime(df_bus['승하차일자'], errors='coerce')

mask_617 = (
    (pd.to_numeric(df_bus['정류소ID'], errors='coerce') == 206000617) &
    (pd.to_numeric(df_bus['정류소번호'], errors='coerce') == 7557)
)

# 1) 삼평동 행 삭제
df_bus = df_bus[
    ~(
        mask_617 &
        (df_bus['행정동'] == '삼평동')
    )
]

# 삭제 후 mask 다시 생성
mask_617 = (
    (pd.to_numeric(df_bus['정류소ID'], errors='coerce') == 206000617) &
    (pd.to_numeric(df_bus['정류소번호'], errors='coerce') == 7557)
)

# 2) 2023년이고 정류소명이 NaN이면 채우기
df_bus.loc[
    mask_617 &
    (df_bus['승하차일자'].dt.year == 2023) &
    (df_bus['정류소명'].isna()),
    '정류소명'
] = '보평중고등학교'

# 3) 2024년이고 정류소명이 NaN이면 채우기
df_bus.loc[
    mask_617 &
    (df_bus['승하차일자'].dt.year == 2024) &
    (df_bus['정류소명'].isna()),
    '정류소명'
] = '성남역.보평중고등학교'

In [61]:
# 잘됐는지 확인 
df_bus[
    (df_bus['정류소명'].notna()) &
    (df_bus['행정동'].isna())
]
# 그래도 아직 na값인 행이 있음

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
17,2023-01-01,성남시,NaN,206000855,7822.0,SK.금강테라스하우스,11,10,1,24
48,2023-01-01,성남시,NaN,204000001,5008.0,고등동우체국.성남농협대왕지점,89,60,29,178
84,2023-01-01,성남시,NaN,204000256,5221.0,교보문고(마을),11,11,0,30
94,2023-01-01,성남시,NaN,205000008,6076.0,구서고.금상초교,389,378,11,244
95,2023-01-01,성남시,NaN,205000160,6074.0,구서고.금상초교,317,303,14,332
...,...,...,...,...,...,...,...,...,...,...
2058599,2025-12-31,성남시,NaN,205000016,06025,하대원동행정복지센터.영성중.검단초,406,360,46,686
2058600,2025-12-31,성남시,NaN,205000152,06024,하대원동행정복지센터.영성중.검단초,731,688,43,352
2058647,2025-12-31,성남시,NaN,204000070,05151,한국폴리텍대학.성남문화예술교육센터,27,23,4,37
2058648,2025-12-31,성남시,NaN,204000080,05149,한국폴리텍대학.성남문화예술교육센터,8,4,4,36
2058688,2025-12-31,성남시,NaN,206000342,07318,현대노블리스,0,0,0,12

| 정류소 ID | 정류소번호 | 연도 / 정류소명 | 기존 행정동 | 수정 행정동 | 수정 사유 |
|---|---|---|---|---|---|
| 206000305 | 7159.0 | 2023: 아름마을.이매고교.효성선경아파트.하나은행<br>2024: 성남역.이매고교.아름마을.효성선경아파트 | NaN | 이매2동 | 정류소명 변경 + 동일 위치 확인 |
| 206000314 | 7303.0 | 2023: 아름마을.이매고교.효성선경아파트.하나은행<br>2024: 성남역.이매고교.아름마을.효성선경아파트 | NaN | 이매2동 | 정류소명 변경 + 동일 위치 확인 |
| 206000530 | 7487.0 | 2023: 백현마을2단지<br>2024: 성남역.백현마을2단지 | NaN | 백현동 | 정류소명 변경 + 동일 위치 확인 |
| 206000537 | 7420.0 | 2023: 백현마을3단지<br>2024: 성남역.백현마을3단지 | NaN | 백현동 | 정류소명 변경 + 동일 위치 확인 |
| 206000616 | 7556.0 | 2023: 보평중고등학교<br>2024: 성남역.보평중고등학교 | 백현동, 삼평동 | 삼평동 유지 / 백현동 삭제 | 중복 매핑 제거 |
| 206000617 | 7557.0 | 2023: 보평중고등학교<br>2024: 성남역.보평중고등학교 | 백현동, 삼평동 | 백현동 유지 / 삼평동 삭제 | 중복 매핑 제거 |

In [62]:
## 성남시가 아닌 행 제거
df_bus = df_bus[
    ~df_bus['정류소명'].isin([
        '고기3리.유원지입구',
        '고기동마을',
        '고기초등학교'
    ])
]

In [63]:
dong_map = {
    '(임시)금토동삼거리': '금토동',
    'SK.금강테라스하우스': '대장동',
    '고등동우체국.성남농협대왕지점': '고등동',
    '고등동행정복지센터.성남농협대왕지점': '고등동',
    '공단치안센터.근로자종합복지관': '상대원동',
    '곽여성병원(마을)': '태평동',
    '교보문고(마을)': '백현동',
    '구미공원.불곡초등학교': '구미동',
    '구미동행정복지센터': '구미동',
    '구서고.금상초교': '금광동',
    '국은교앞': '운중동',
    '금상초교.이편한세상3단지': '금광동',
    '금상초교.이편한세상5단지': '금광동',
    '나라기록관.코이카': '시흥동',
    '남한산성공원입구': '양지동',
    '남한산성공원입구.양지파출소': '양지동',
    '노블빌리지': '구미동',
    '농수산물센터사거리': '구미동',
    '농수산물센터사거리.LG트윈하우스': '구미동',
    '단대오거리역.성남시박물관': '신흥동',
    '단대오거리역.세이브존.성남시박물관': '신흥동',
    '대하초등학교.중원유스센터': '하대원동',
    '더블트리바이힐튼호텔.잡월드': '정자동',
    '동국대한방병원.신성아파트.수내도서관': '수내동',
    '동원동종점.모드니': '동원동',
    '목련마을SK아파트.성남시차량등록사업소': '야탑동',
    '무지개도서관.구미파출소.건영아파트': '구미동',
    '무지개마을사거리': '구미동',
    '백현동종점': '백현동'
}

df_bus['행정동'] = df_bus['행정동'].fillna(
    df_bus['정류소명'].map(dong_map)
)

In [64]:
dong_map_update = {
    '다이소앞': '구미동',
    '벽산아파트': '수내동',
    '보평중고등학교': '백현동',
    '봇들마을7.8단지.롯데마트판교점': '삼평동',
    '분당경영고.한라아파트': '금곡동',
    '분당아테나': '수내동',
    '분당아테라': '수내동',
    '사송동.한국수자원공사': '사송동',
    '사송동.한국수자원공사(마을)': '사송동',
    '상대원119안전센터.성남공단우체국': '상대원동',
    '새마을연수원입구': '율동',
    '서현유스센터.양영디지털고등학교': '서현동',
    '선경아파트.성남중원경찰서.중원구보건소': '상대원동',
    '선텍시티2차': '상대원동',
    '성남고등공공주택지구.동편': '고등동',
    '성남고등공공주택지구.서편': '고등동',
    '성남금융고': '야탑동',
    '성남금융고.중탑초교': '야탑동',
    '성남냉동': '하대원동',
    '성남농협대왕지점.고등동우체국': '고등동',
    '성남물빛정원남측.노블빌리지': '구미동',
    '성남물빛정원서측.한국토지주택공사': '구미동',
    '성남북초등학교.산성동행정복지센터.산성역자이4단지': '산성동',
    '성남시근로자종합복지관': '상대원동',
    '성남시여성비전센터.삼성생명.한국사회적기업진흥원': '태평동',
    '성남시여성비전센터.성남수정새마을금고.한국사회적기업진흥원': '태평동',
    '성남시의료원.신흥1동행정복지센터.성남아트리움': '신흥동',
    '성남시장례문화사업소': '갈현동',
    '성남시장례문화사업소.장례식장입구': '갈현동',
    '성남역': '백현동'
}

df_bus['행정동'] = df_bus['행정동'].fillna(
    df_bus['정류소명'].map(dong_map_update)
)

In [65]:
dong_map_update2 = {
    '성남역': '백현동',
    '성남역.보평중고등학교': '백현동',
    '성남중원경찰서': '상대원동',
    '성남혜은학교.수정유스센터.산성역자이3단지': '신흥동',
    '성보경영고등학교': '단대동',
    '세이브존.성남시박물관': '신흥동',
    '셀레스빌아파트.포레스티아중문': '신흥동',
    '수내2동행정복지센터': '수내동',
    '수내고등학교.수내도서관': '수내동',
    '수정구청.산성역자이2단지': '신흥동',
    '수정구청.포레스티아서문': '신흥동',
    '수정초등학교': '수진동',
    '수진동성당': '수진동',
    '순환도시친환경세상순환자원홍보관': '석운동',
    '쉐보레분당서비스센터': '금곡동',
    '시흥동농협창고': '시흥동',
    '시흥사거리.고등공공주택지구': '시흥동',
    '신지교회': '성남동',
    '아튼빌아파트.중원유스센터': '하대원동',
    '에스콰이어': '상대원동',
    '옛근로자종합복지관': '성남동',
    '오리삼거리(마을)': '구미동',
    '우성아파트': '정자동',
    '위례31단지.위례포레샤인후문': '창곡동',
    '위례31단지정문': '창곡동',
    '위례동행정복지센터.위례보미리즌빌': '창곡동',
    '위례동행정복지센터.위례아트리버푸르지오': '창곡동',
    '위례자연앤래미안e편한세상.위례한빛중학교': '창곡동',
    '위례자연앤래미안e편한세상.위례힐스테이트': '창곡동',
    '위례자이아파트': '창곡동'
}

# 행정동 NULL만 채우기
df_bus['행정동'] = df_bus['행정동'].fillna(
    df_bus['정류소명'].map(dong_map_update2)
)

# 왕재건설중기 행 삭제
df_bus = df_bus[
    df_bus['정류소명'] != '왕재건설중기'
]

In [66]:
dong_map_update3 = {
    '위례자이후문': '창곡동',
    '위례중앙초등학교': '창곡동',
    '위례포레샤인.위례31단지후문': '창곡동',
    '위례한빛고등학교': '창곡동',
    '위례한빛초.래미안.힐스테이트.한빛마을': '창곡동',
    '위례한빛초교.힐스테이트후문.한빛마을': '창곡동',
    '위례호반베르디움': '창곡동',
    '위례힐스테이트정문': '창곡동',
    '위례힐스테이트후문.위례한빛초등학교': '창곡동',
    '이노밸리.포스코ICT': '삼평동',
    '이매역.진흥아파트.동신아파트': '이매동',
    '이우중고등학교.주성카센타': '동원동',
    '이지더원.삼평동행정복지센터': '삼평동',
    '이편한세상5단지': '금광동',
    '이편한세상금빛그랑메종': '금광동',
    '자연앤센트럴자이': '창곡동',
    '자연앤센트럴자이정문': '창곡동',
    '정자유스센터.분당클리닉': '정자동',
    '주공12단지': '구미동',
    '주공7단지앞.치매안심센터': '정자동',
    '주공7단지앞.한솔종합사회복지관.치매안심센터': '정자동',
    '중동고개.제일초교': '중앙동',
    '중앙동사거리': '중앙동',
    '중원구청.성남소방서': '성남동',
    '진로아파트': '단대동',
    '창조밸리교': '금곡동',
    '창조밸리교(경유)': '금곡동',
    '청솔마을.계룡아파트': '금곡동',
    '청솔마을.화인아파트': '금곡동',
    '파크뷰아파트.정자유스센터': '정자동'
}

df_bus['행정동'] = df_bus['행정동'].fillna(
    df_bus['정류소명'].map(dong_map_update3)
)

In [67]:
dong_map_update4 = {
    '판교고.송현초.삼평동행정복지센터': '삼평동',
    '판교대장초?중학교': '대장동',
    '판교더샵포레스트11단지': '대장동',
    '판교청소년수련관.판교종합사회복지관': '판교동',
    '판교퍼스트힐푸르지오2단지': '대장동',
    '포레스티아서문.신흥2동행정복지센터.산성역자이2단지': '신흥동',
    '푸른마을신성아파트.수내도서관': '수내동',
    '하대원동행정복지센터.영성중.검단초': '하대원동',
    '한국폴리텍대학.성남문화예술교육센터': '산성동',
    '한양수자인성남마크뷰.황성게이트볼장': '금광동',
    '헬스케어혁신파크.(구)가스공사': '정자동',
    '현대노블리스': '구미동',
    '힐스테이트판교엘포레6단지후문': '대장동'
}

df_bus['행정동'] = df_bus['행정동'].fillna(
    df_bus['정류소명'].map(dong_map_update4)
)

In [68]:
# 잘됐는지 확인
df_bus[
    (df_bus['정류소명'].notna()) &
    (df_bus['행정동'].isna())
]

Empty DataFrame
Columns: [승하차일자, 관할관청, 행정동, 정류소ID, 정류소번호, 정류소명, 승차합계, 초승, 환승, 하차]
Index: []

In [69]:
df_bus[df_bus['정류소명'].isna()]

Empty DataFrame
Columns: [승하차일자, 관할관청, 행정동, 정류소ID, 정류소번호, 정류소명, 승차합계, 초승, 환승, 하차]
Index: []

In [70]:
df_bus[df_bus['행정동'].isna()]

Empty DataFrame
Columns: [승하차일자, 관할관청, 행정동, 정류소ID, 정류소번호, 정류소명, 승차합계, 초승, 환승, 하차]
Index: []

In [71]:
df_bus.duplicated().sum()

np.int64(757362)

In [72]:
df_bus= df_bus.drop_duplicates()
df_bus

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
0,2023-01-01,성남시,성남동,205000120,6163.0,(구)성남동주민센터,103,99,4,106
1,2023-01-01,성남시,서현1동,206000436,7387.0,AK플라자2층,353,203,150,454
2,2023-01-01,성남시,삼평동,206000677,7034.0,H스퀘어.삼환하이펙스,1,1,0,25
4,2023-01-01,성남시,삼평동,206000678,7479.0,H스퀘어.삼환하이펙스,15,14,1,2
6,2023-01-01,성남시,시흥동,204000342,5333.0,I_SQUARE.창업주택,5,3,2,49
...,...,...,...,...,...,...,...,...,...,...
2058744,2025-12-31,성남시,복정동,204000234,05299,힐스테이트위례정문,17,17,0,49
2058746,2025-12-31,성남시,복정동,204000201,05298,힐스테이트위례후문.위례한빛초등학교,27,26,1,19
2058747,2025-12-31,성남시,운중동,206000854,07830,힐스테이트판교엘포레4단지,472,466,6,153
2058748,2025-12-31,성남시,운중동,206000472,07821,힐스테이트판교엘포레6단지,140,137,3,83
2058749,2025-12-31,성남시,운중동,206000646,07820,힐스테이트판교엘포레6단지.판교SK뷰테라스,258,258,0,59

In [73]:
df_bus.duplicated().sum()

np.int64(0)

In [75]:
df_bus['승하차일자'] = pd.to_datetime(df_bus['승하차일자']).dt.to_period('M')

In [76]:
df_bus

,승하차일자,관할관청,행정동,정류소ID,정류소번호,정류소명,승차합계,초승,환승,하차
0,2023-01,성남시,성남동,205000120,6163.0,(구)성남동주민센터,103,99,4,106
1,2023-01,성남시,서현1동,206000436,7387.0,AK플라자2층,353,203,150,454
2,2023-01,성남시,삼평동,206000677,7034.0,H스퀘어.삼환하이펙스,1,1,0,25
4,2023-01,성남시,삼평동,206000678,7479.0,H스퀘어.삼환하이펙스,15,14,1,2
6,2023-01,성남시,시흥동,204000342,5333.0,I_SQUARE.창업주택,5,3,2,49
...,...,...,...,...,...,...,...,...,...,...
2058744,2025-12,성남시,복정동,204000234,05299,힐스테이트위례정문,17,17,0,49
2058746,2025-12,성남시,복정동,204000201,05298,힐스테이트위례후문.위례한빛초등학교,27,26,1,19
2058747,2025-12,성남시,운중동,206000854,07830,힐스테이트판교엘포레4단지,472,466,6,153
2058748,2025-12,성남시,운중동,206000472,07821,힐스테이트판교엘포레6단지,140,137,3,83
2058749,2025-12,성남시,운중동,206000646,07820,힐스테이트판교엘포레6단지.판교SK뷰테라스,258,258,0,59

In [77]:
df_bus.to_csv('2차전처리_버스데이터.csv', index=False, encoding='utf-8-sig')